version: '2'

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - .:/etc/prometheus/
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - back-tier

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    # volumes:
    #   - grafana_data:/var/lib/grafana
    # env_file:
    #   - config.monitoring
    networks:
      - back-tier
      - front-tier
